apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "perf.fullname" . }}-kafka
  labels:
{{ include "perf.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "perf.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "perf.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "perf.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-kafka
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag }}"
          imagePullPolicy: {{ .Values.kafka.image.pullPolicy }}
          command: ["sleep", "100000"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
