{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "perf.serviceAccountName" . }}
  labels:
{{ include "perf.labels" . | indent 4 }}
{{- end -}}
